name: CI

on:
  push:
    branches: [main, develop]
    paths:
      - 'toggl_mcp/**'
      - 'pyproject.toml'
      - 'tests/**'
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: "pyproject.toml"
    
    - name: Build package
      run: uv build
    
    - name: Run tests
      run: uv run pytest tests/
