name: Test Publish to TestPyPI

on:
  push:
    branches: [main, develop]
    paths:
      - 'toggl_mcp/**'
      - 'pyproject.toml'
      - 'setup.py'
  pull_request:
    branches: [main]
  workflow_dispatch:  # Allow manual trigger

jobs:
  test-build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: "pyproject.toml"
    
    - name: Set up Python
      run: uv python install 3.x
    
    - name: Install dependencies
      run: |
        uv venv
        uv pip install -e .
    
    - name: Run tests
      run: |
        # Add your test command here if you have tests
        # uv run pytest tests/ || true
        uv run python -c "import toggl_mcp; print('Package imports successfully')"
    
    - name: Build package
      run: uv build
    
    - name: Publish to TestPyPI
      # Only publish on main branch pushes, not PRs
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository-url: https://test.pypi.org/legacy/
        skip-existing: true  # Skip if version already exists
