name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest pytest-asyncio
    
    - name: Test imports
      run: |
        python -c "from toggl_client import TogglClient"
        python -c "from tools import get_all_tools"
        python -c "from main import create_toggl_server"
    
    - name: Run connection test (dry run)
      env:
        TOGGL_API_TOKEN: "dummy_token_for_test"
      run: |
        # This will fail to connect but will test the code structure
        python test_connection.py || true
