name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.13']  # Test on latest Python only

    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: "pyproject.toml"
    
    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        uv venv
        uv pip install -e .
    
    - name: Test module imports
      run: |
        uv run python -c "from toggl_mcp.toggl_client import TogglClient; print('✓ TogglClient import successful')"
        uv run python -c "from toggl_mcp.main import run, setup_and_run; print('✓ Main functions import successful')"
        uv run python -c "import toggl_mcp; print('✓ Package import successful')"
    
    - name: Run basic tests
      env:
        TOGGL_API_TOKEN: ${{ secrets.TOGGL_API_TOKEN }}
      run: |
        # Test that the module structure is correct
        uv run python -c "from toggl_mcp.toggl_client import TogglClient; from toggl_mcp.main import run, setup_and_run; print('✓ All imports working correctly')"
        
        # Run connection test if API token is available
        if [ ! -z "$TOGGL_API_TOKEN" ]; then
          echo "Running connection test with API token..."
          uv run python test_connection.py || echo "Connection test failed (check API token)"
        else
          echo "Skipping connection test (no API token)"
        fi